---
name: Run tests
on:
  pull_request: ~
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  pnpm-tests:
    name: pnpm test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm test

  validate-renovate-config:
    name: Validate Renovate Config
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - run:
          pnpm dlx --allow-build=better-sqlite3 --allow-build=core-js-pure --allow-build=dtrace-provider
          --allow-build=protobufjs --allow-build=re2 --package=renovate@${{ env.RENOVATE_VERSION }} --
          renovate-config-validator renovate.json default.json
        env:
          # renovate: datasource=npm depName=renovate
          RENOVATE_VERSION: "43.257.2"
