---
name: Run tests
on:
  pull_request: ~
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  pnpm-tests:
    name: pnpm test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm test

  validate-renovate-config:
    name: Validate Renovate Config
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - run:
          pnpm dlx --allow-build=better-sqlite3 --allow-build=core-js-pure --allow-build=dtrace-provider
          --allow-build=protobufjs --allow-build=re2 --package=renovate@${{ env.RENOVATE_VERSION }} --
          renovate-config-validator renovate.json default.json
        env:
          # renovate: datasource=npm depName=renovate
          RENOVATE_VERSION: "43.271.2"

  validate-oxfmt-config:
    name: Validate oxfmt-config
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - run: pnpm build
        working-directory: packages/oxfmt-config/
