---
name: Run tests
on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  pnpm-tests:
    name: pnpm test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm test

  validate-renovate-config:
    name: Validate Renovate Config
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
      - run:
          pnpm dlx --allow-build=better-sqlite3 --allow-build=core-js-pure --allow-build=dtrace-provider
          --allow-build=protobufjs --allow-build=re2 --package=renovate@${{ env.RENOVATE_VERSION }} --
          renovate-config-validator renovate.json default.json
        env:
          # renovate: datasource=npm depName=renovate
          RENOVATE_VERSION: "43.141.5"
